//
//Copyright 2026 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.32.1
// source: dapr/proto/internals/v1/workflow_xns.proto

package internals

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkflowOpKind identifies which workflow operation the forward represents.
// The payload field carries the operation-specific marshalled request from
// durabletask-go (e.g. TerminateRequest, RaiseEventRequest, PurgeInstancesRequest).
type WorkflowOpKind int32

const (
	WorkflowOpKind_WORKFLOW_OP_UNSPECIFIED WorkflowOpKind = 0
	WorkflowOpKind_WORKFLOW_OP_SCHEDULE    WorkflowOpKind = 1
	WorkflowOpKind_WORKFLOW_OP_TERMINATE   WorkflowOpKind = 2
	WorkflowOpKind_WORKFLOW_OP_RAISE       WorkflowOpKind = 3
	WorkflowOpKind_WORKFLOW_OP_PAUSE       WorkflowOpKind = 4
	WorkflowOpKind_WORKFLOW_OP_RESUME      WorkflowOpKind = 5
	WorkflowOpKind_WORKFLOW_OP_PURGE       WorkflowOpKind = 6
	WorkflowOpKind_WORKFLOW_OP_GET         WorkflowOpKind = 7
	WorkflowOpKind_WORKFLOW_OP_RERUN       WorkflowOpKind = 8
)

// Enum value maps for WorkflowOpKind.
var (
	WorkflowOpKind_name = map[int32]string{
		0: "WORKFLOW_OP_UNSPECIFIED",
		1: "WORKFLOW_OP_SCHEDULE",
		2: "WORKFLOW_OP_TERMINATE",
		3: "WORKFLOW_OP_RAISE",
		4: "WORKFLOW_OP_PAUSE",
		5: "WORKFLOW_OP_RESUME",
		6: "WORKFLOW_OP_PURGE",
		7: "WORKFLOW_OP_GET",
		8: "WORKFLOW_OP_RERUN",
	}
	WorkflowOpKind_value = map[string]int32{
		"WORKFLOW_OP_UNSPECIFIED": 0,
		"WORKFLOW_OP_SCHEDULE":    1,
		"WORKFLOW_OP_TERMINATE":   2,
		"WORKFLOW_OP_RAISE":       3,
		"WORKFLOW_OP_PAUSE":       4,
		"WORKFLOW_OP_RESUME":      5,
		"WORKFLOW_OP_PURGE":       6,
		"WORKFLOW_OP_GET":         7,
		"WORKFLOW_OP_RERUN":       8,
	}
)

func (x WorkflowOpKind) Enum() *WorkflowOpKind {
	p := new(WorkflowOpKind)
	*p = x
	return p
}

func (x WorkflowOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_internals_v1_workflow_xns_proto_enumTypes[0].Descriptor()
}

func (WorkflowOpKind) Type() protoreflect.EnumType {
	return &file_dapr_proto_internals_v1_workflow_xns_proto_enumTypes[0]
}

func (x WorkflowOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowOpKind.Descriptor instead.
func (WorkflowOpKind) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_internals_v1_workflow_xns_proto_rawDescGZIP(), []int{0}
}

type ForwardOpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// operation indicates which workflow operation to invoke on the receiving
	// side.
	Operation WorkflowOpKind `protobuf:"varint,1,opt,name=operation,proto3,enum=dapr.proto.internals.v1.WorkflowOpKind" json:"operation,omitempty"`
	// instance_id is the workflow instance the operation applies to (or the
	// new instance ID for schedule).
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// target_app_id is the app within the receiving namespace that hosts the
	// workflow. The receiving sidecar verifies this matches its own appID.
	TargetAppId string `protobuf:"bytes,3,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	// payload carries the marshalled durabletask request proto for the op.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// forward_id is a deterministic dedup key derived from (operation,
	// instance_id, target_app_id, target_app_namespace, payload). Both sides
	// use it to short-circuit duplicate forwards (e.g. after a reminder retry).
	ForwardId string `protobuf:"bytes,5,opt,name=forward_id,json=forwardId,proto3" json:"forward_id,omitempty"`
	// target_app_namespace is the Dapr namespace hosting target_app_id. The
	// outbound forwarder uses it to dial the right peer daprd; the receiving
	// side verifies it matches.
	TargetAppNamespace string `protobuf:"bytes,6,opt,name=target_app_namespace,json=targetAppNamespace,proto3" json:"target_app_namespace,omitempty"`
}

func (x *ForwardOpRequest) Reset() {
	*x = ForwardOpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOpRequest) ProtoMessage() {}

func (x *ForwardOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOpRequest.ProtoReflect.Descriptor instead.
func (*ForwardOpRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_internals_v1_workflow_xns_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardOpRequest) GetOperation() WorkflowOpKind {
	if x != nil {
		return x.Operation
	}
	return WorkflowOpKind_WORKFLOW_OP_UNSPECIFIED
}

func (x *ForwardOpRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ForwardOpRequest) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *ForwardOpRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardOpRequest) GetForwardId() string {
	if x != nil {
		return x.ForwardId
	}
	return ""
}

func (x *ForwardOpRequest) GetTargetAppNamespace() string {
	if x != nil {
		return x.TargetAppNamespace
	}
	return ""
}

// ForwardOpResponse returns the operation result back through the durable
// reminder on the source side. payload is the marshalled durabletask
// response proto for ops that return one (Get, Purge); empty for the rest.
type ForwardOpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ForwardOpResponse) Reset() {
	*x = ForwardOpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOpResponse) ProtoMessage() {}

func (x *ForwardOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOpResponse.ProtoReflect.Descriptor instead.
func (*ForwardOpResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_internals_v1_workflow_xns_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardOpResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_dapr_proto_internals_v1_workflow_xns_proto protoreflect.FileDescriptor

var file_dapr_proto_internals_v1_workflow_xns_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x5f, 0x78, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x89, 0x02, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x4f, 0x70, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x30, 0x0a, 0x14, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x2d, 0x0a, 0x11, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x2a, 0xeb, 0x01, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f,
	0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x18, 0x0a, 0x14, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4f, 0x50, 0x5f,
	0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x57, 0x4f,
	0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4f, 0x50, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f,
	0x57, 0x5f, 0x4f, 0x50, 0x5f, 0x52, 0x41, 0x49, 0x53, 0x45, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11,
	0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4f, 0x50, 0x5f, 0x50, 0x41, 0x55, 0x53,
	0x45, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f,
	0x4f, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4d, 0x45, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x57,
	0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4f, 0x50, 0x5f, 0x50, 0x55, 0x52, 0x47, 0x45,
	0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4f,
	0x50, 0x5f, 0x47, 0x45, 0x54, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x4f, 0x52, 0x4b, 0x46,
	0x4c, 0x4f, 0x57, 0x5f, 0x4f, 0x50, 0x5f, 0x52, 0x45, 0x52, 0x55, 0x4e, 0x10, 0x08, 0x32, 0x75,
	0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x4e,
	0x53, 0x12, 0x62, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x12, 0x29,
	0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x4f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x73, 0x2f, 0x76, 0x31, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dapr_proto_internals_v1_workflow_xns_proto_rawDescOnce sync.Once
	file_dapr_proto_internals_v1_workflow_xns_proto_rawDescData = file_dapr_proto_internals_v1_workflow_xns_proto_rawDesc
)

func file_dapr_proto_internals_v1_workflow_xns_proto_rawDescGZIP() []byte {
	file_dapr_proto_internals_v1_workflow_xns_proto_rawDescOnce.Do(func() {
		file_dapr_proto_internals_v1_workflow_xns_proto_rawDescData = protoimpl.X.CompressGZIP(file_dapr_proto_internals_v1_workflow_xns_proto_rawDescData)
	})
	return file_dapr_proto_internals_v1_workflow_xns_proto_rawDescData
}

var file_dapr_proto_internals_v1_workflow_xns_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dapr_proto_internals_v1_workflow_xns_proto_goTypes = []interface{}{
	(WorkflowOpKind)(0),       // 0: dapr.proto.internals.v1.WorkflowOpKind
	(*ForwardOpRequest)(nil),  // 1: dapr.proto.internals.v1.ForwardOpRequest
	(*ForwardOpResponse)(nil), // 2: dapr.proto.internals.v1.ForwardOpResponse
}
var file_dapr_proto_internals_v1_workflow_xns_proto_depIdxs = []int32{
	0, // 0: dapr.proto.internals.v1.ForwardOpRequest.operation:type_name -> dapr.proto.internals.v1.WorkflowOpKind
	1, // 1: dapr.proto.internals.v1.WorkflowCrossNS.ForwardOp:input_type -> dapr.proto.internals.v1.ForwardOpRequest
	2, // 2: dapr.proto.internals.v1.WorkflowCrossNS.ForwardOp:output_type -> dapr.proto.internals.v1.ForwardOpResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dapr_proto_internals_v1_workflow_xns_proto_init() }
func file_dapr_proto_internals_v1_workflow_xns_proto_init() {
	if File_dapr_proto_internals_v1_workflow_xns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardOpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardOpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dapr_proto_internals_v1_workflow_xns_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapr_proto_internals_v1_workflow_xns_proto_goTypes,
		DependencyIndexes: file_dapr_proto_internals_v1_workflow_xns_proto_depIdxs,
		EnumInfos:         file_dapr_proto_internals_v1_workflow_xns_proto_enumTypes,
		MessageInfos:      file_dapr_proto_internals_v1_workflow_xns_proto_msgTypes,
	}.Build()
	File_dapr_proto_internals_v1_workflow_xns_proto = out.File
	file_dapr_proto_internals_v1_workflow_xns_proto_rawDesc = nil
	file_dapr_proto_internals_v1_workflow_xns_proto_goTypes = nil
	file_dapr_proto_internals_v1_workflow_xns_proto_depIdxs = nil
}
