// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: dapr/proto/scheduler/v1/broadcast.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BroadcastJobEventType is the type of the event why this job is being
// broadcast.
type BroadcastJobEventType int32

const (
	// BROADCAST_JOB_EVENT_PUT is the event type for a job being created or
	// updated.
	BroadcastJobEventType_BROADCAST_JOB_EVENT_PUT BroadcastJobEventType = 0
	// BROADCAST_JOB_EVENT_DELETE is the event type for a job being deleted.
	BroadcastJobEventType_BROADCAST_JOB_EVENT_DELETE BroadcastJobEventType = 1
	// BROADCAST_JOB_EVENT_TRIGGER is the event type for a job being triggered.
	BroadcastJobEventType_BROADCAST_JOB_EVENT_TRIGGER BroadcastJobEventType = 2
)

// Enum value maps for BroadcastJobEventType.
var (
	BroadcastJobEventType_name = map[int32]string{
		0: "BROADCAST_JOB_EVENT_PUT",
		1: "BROADCAST_JOB_EVENT_DELETE",
		2: "BROADCAST_JOB_EVENT_TRIGGER",
	}
	BroadcastJobEventType_value = map[string]int32{
		"BROADCAST_JOB_EVENT_PUT":     0,
		"BROADCAST_JOB_EVENT_DELETE":  1,
		"BROADCAST_JOB_EVENT_TRIGGER": 2,
	}
)

func (x BroadcastJobEventType) Enum() *BroadcastJobEventType {
	p := new(BroadcastJobEventType)
	*p = x
	return p
}

func (x BroadcastJobEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastJobEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_scheduler_v1_broadcast_proto_enumTypes[0].Descriptor()
}

func (BroadcastJobEventType) Type() protoreflect.EnumType {
	return &file_dapr_proto_scheduler_v1_broadcast_proto_enumTypes[0]
}

func (x BroadcastJobEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastJobEventType.Descriptor instead.
func (BroadcastJobEventType) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_scheduler_v1_broadcast_proto_rawDescGZIP(), []int{0}
}

// BroadcastJobDataWrapper is a canonical wrapper for the data of a broadcast
// job which is sent to clients from the Scheduler. Contains CRUD events for
// the broadcast job.
// This message will set on the data field of the job when being broadcast from
// Scheduler to compatible clients.
type BroadcastJobDataWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is the type of the event which is causing this job to be send to the
	// client.
	Type BroadcastJobEventType `protobuf:"varint,1,opt,name=type,proto3,enum=dapr.proto.scheduler.v1.BroadcastJobEventType" json:"type,omitempty"`
	// data contains the actual data of the job. It may be wrapped in another
	// message, depending on the type of broadcast job.
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BroadcastJobDataWrapper) Reset() {
	*x = BroadcastJobDataWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastJobDataWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastJobDataWrapper) ProtoMessage() {}

func (x *BroadcastJobDataWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastJobDataWrapper.ProtoReflect.Descriptor instead.
func (*BroadcastJobDataWrapper) Descriptor() ([]byte, []int) {
	return file_dapr_proto_scheduler_v1_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastJobDataWrapper) GetType() BroadcastJobEventType {
	if x != nil {
		return x.Type
	}
	return BroadcastJobEventType_BROADCAST_JOB_EVENT_PUT
}

func (x *BroadcastJobDataWrapper) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// TargetBroadcast are job types which are "broadcast", meaning they are sent
// to all clients who support this target on connection, and when the job is
// created. On delete, the job is signalled to all matching clients that the
// job has been deleted with an empty data payload.
type TargetBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Broadcast:
	//
	//	*TargetBroadcast_DurableActorId
	Broadcast isTargetBroadcast_Broadcast `protobuf_oneof:"broadcast"`
}

func (x *TargetBroadcast) Reset() {
	*x = TargetBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetBroadcast) ProtoMessage() {}

func (x *TargetBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetBroadcast.ProtoReflect.Descriptor instead.
func (*TargetBroadcast) Descriptor() ([]byte, []int) {
	return file_dapr_proto_scheduler_v1_broadcast_proto_rawDescGZIP(), []int{1}
}

func (m *TargetBroadcast) GetBroadcast() isTargetBroadcast_Broadcast {
	if m != nil {
		return m.Broadcast
	}
	return nil
}

func (x *TargetBroadcast) GetDurableActorId() *TargetDurableActorID {
	if x, ok := x.GetBroadcast().(*TargetBroadcast_DurableActorId); ok {
		return x.DurableActorId
	}
	return nil
}

type isTargetBroadcast_Broadcast interface {
	isTargetBroadcast_Broadcast()
}

type TargetBroadcast_DurableActorId struct {
	// TargetDurableActorID is the message which holds broadcast durable actor
	// ID for an Actor Subscription.
	// The data field of the job must be of type `common.InvokeRequest`, where
	// the `.HttpExtension.Verb` will always be ignored, in favour of a POST
	// when the durable actor is invoked.
	DurableActorId *TargetDurableActorID `protobuf:"bytes,1,opt,name=durable_actor_id,json=durableActorId,proto3,oneof"`
}

func (*TargetBroadcast_DurableActorId) isTargetBroadcast_Broadcast() {}

// TargetDurableActorID is the message which holds broadcast durable actor ID
// jobs.
type TargetDurableActorID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the actor ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is the actor type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *TargetDurableActorID) Reset() {
	*x = TargetDurableActorID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetDurableActorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDurableActorID) ProtoMessage() {}

func (x *TargetDurableActorID) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDurableActorID.ProtoReflect.Descriptor instead.
func (*TargetDurableActorID) Descriptor() ([]byte, []int) {
	return file_dapr_proto_scheduler_v1_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *TargetDurableActorID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TargetDurableActorID) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_dapr_proto_scheduler_v1_broadcast_proto protoreflect.FileDescriptor

var file_dapr_proto_scheduler_v1_broadcast_proto_rawDesc = []byte{
	0x0a, 0x27, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01,
	0x0a, 0x17, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x44, 0x61,
	0x74, 0x61, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x79, 0x0a, 0x0f, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x59, 0x0a, 0x10, 0x64, 0x75,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x22, 0x3a, 0x0a, 0x14, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x75, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x75,
	0x0a, 0x15, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x52, 0x4f, 0x41, 0x44,
	0x43, 0x41, 0x53, 0x54, 0x5f, 0x4a, 0x4f, 0x42, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x50,
	0x55, 0x54, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53,
	0x54, 0x5f, 0x4a, 0x4f, 0x42, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53,
	0x54, 0x5f, 0x4a, 0x4f, 0x42, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x52, 0x49, 0x47,
	0x47, 0x45, 0x52, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dapr_proto_scheduler_v1_broadcast_proto_rawDescOnce sync.Once
	file_dapr_proto_scheduler_v1_broadcast_proto_rawDescData = file_dapr_proto_scheduler_v1_broadcast_proto_rawDesc
)

func file_dapr_proto_scheduler_v1_broadcast_proto_rawDescGZIP() []byte {
	file_dapr_proto_scheduler_v1_broadcast_proto_rawDescOnce.Do(func() {
		file_dapr_proto_scheduler_v1_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_dapr_proto_scheduler_v1_broadcast_proto_rawDescData)
	})
	return file_dapr_proto_scheduler_v1_broadcast_proto_rawDescData
}

var file_dapr_proto_scheduler_v1_broadcast_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dapr_proto_scheduler_v1_broadcast_proto_goTypes = []interface{}{
	(BroadcastJobEventType)(0),      // 0: dapr.proto.scheduler.v1.BroadcastJobEventType
	(*BroadcastJobDataWrapper)(nil), // 1: dapr.proto.scheduler.v1.BroadcastJobDataWrapper
	(*TargetBroadcast)(nil),         // 2: dapr.proto.scheduler.v1.TargetBroadcast
	(*TargetDurableActorID)(nil),    // 3: dapr.proto.scheduler.v1.TargetDurableActorID
	(*anypb.Any)(nil),               // 4: google.protobuf.Any
}
var file_dapr_proto_scheduler_v1_broadcast_proto_depIdxs = []int32{
	0, // 0: dapr.proto.scheduler.v1.BroadcastJobDataWrapper.type:type_name -> dapr.proto.scheduler.v1.BroadcastJobEventType
	4, // 1: dapr.proto.scheduler.v1.BroadcastJobDataWrapper.data:type_name -> google.protobuf.Any
	3, // 2: dapr.proto.scheduler.v1.TargetBroadcast.durable_actor_id:type_name -> dapr.proto.scheduler.v1.TargetDurableActorID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dapr_proto_scheduler_v1_broadcast_proto_init() }
func file_dapr_proto_scheduler_v1_broadcast_proto_init() {
	if File_dapr_proto_scheduler_v1_broadcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastJobDataWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetDurableActorID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TargetBroadcast_DurableActorId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dapr_proto_scheduler_v1_broadcast_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dapr_proto_scheduler_v1_broadcast_proto_goTypes,
		DependencyIndexes: file_dapr_proto_scheduler_v1_broadcast_proto_depIdxs,
		EnumInfos:         file_dapr_proto_scheduler_v1_broadcast_proto_enumTypes,
		MessageInfos:      file_dapr_proto_scheduler_v1_broadcast_proto_msgTypes,
	}.Build()
	File_dapr_proto_scheduler_v1_broadcast_proto = out.File
	file_dapr_proto_scheduler_v1_broadcast_proto_rawDesc = nil
	file_dapr_proto_scheduler_v1_broadcast_proto_goTypes = nil
	file_dapr_proto_scheduler_v1_broadcast_proto_depIdxs = nil
}
