{{- if eq .Values.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: dapr-sidecar-injector-cert
  labels:
    app: dapr-sidecar-injector
    {{- range $key, $value := .Values.global.k8sLabels }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
data:
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: dapr-sidecar-injector
  labels:
    app: dapr-sidecar-injector
    {{- range $key, $value := .Values.global.k8sLabels }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
webhooks:
- name: sidecar-injector.dapr.io
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: dapr-sidecar-injector
      path: "/mutate"
    caBundle:
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  failurePolicy: {{ .Values.webhookFailurePolicy}}
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
{{- end }}
