//
//Copyright 2026 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dapr/proto/internals/v1/workflow_xns.proto

package internalsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dapr/dapr/pkg/proto/internals/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkflowCrossNSName is the fully-qualified name of the WorkflowCrossNS service.
	WorkflowCrossNSName = "dapr.proto.internals.v1.WorkflowCrossNS"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkflowCrossNSForwardOpProcedure is the fully-qualified name of the WorkflowCrossNS's ForwardOp
	// RPC.
	WorkflowCrossNSForwardOpProcedure = "/dapr.proto.internals.v1.WorkflowCrossNS/ForwardOp"
)

// WorkflowCrossNSClient is a client for the dapr.proto.internals.v1.WorkflowCrossNS service.
type WorkflowCrossNSClient interface {
	ForwardOp(context.Context, *connect.Request[v1.ForwardOpRequest]) (*connect.Response[v1.ForwardOpResponse], error)
}

// NewWorkflowCrossNSClient constructs a client for the dapr.proto.internals.v1.WorkflowCrossNS
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkflowCrossNSClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkflowCrossNSClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workflowCrossNSMethods := v1.File_dapr_proto_internals_v1_workflow_xns_proto.Services().ByName("WorkflowCrossNS").Methods()
	return &workflowCrossNSClient{
		forwardOp: connect.NewClient[v1.ForwardOpRequest, v1.ForwardOpResponse](
			httpClient,
			baseURL+WorkflowCrossNSForwardOpProcedure,
			connect.WithSchema(workflowCrossNSMethods.ByName("ForwardOp")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workflowCrossNSClient implements WorkflowCrossNSClient.
type workflowCrossNSClient struct {
	forwardOp *connect.Client[v1.ForwardOpRequest, v1.ForwardOpResponse]
}

// ForwardOp calls dapr.proto.internals.v1.WorkflowCrossNS.ForwardOp.
func (c *workflowCrossNSClient) ForwardOp(ctx context.Context, req *connect.Request[v1.ForwardOpRequest]) (*connect.Response[v1.ForwardOpResponse], error) {
	return c.forwardOp.CallUnary(ctx, req)
}

// WorkflowCrossNSHandler is an implementation of the dapr.proto.internals.v1.WorkflowCrossNS
// service.
type WorkflowCrossNSHandler interface {
	ForwardOp(context.Context, *connect.Request[v1.ForwardOpRequest]) (*connect.Response[v1.ForwardOpResponse], error)
}

// NewWorkflowCrossNSHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkflowCrossNSHandler(svc WorkflowCrossNSHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workflowCrossNSMethods := v1.File_dapr_proto_internals_v1_workflow_xns_proto.Services().ByName("WorkflowCrossNS").Methods()
	workflowCrossNSForwardOpHandler := connect.NewUnaryHandler(
		WorkflowCrossNSForwardOpProcedure,
		svc.ForwardOp,
		connect.WithSchema(workflowCrossNSMethods.ByName("ForwardOp")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dapr.proto.internals.v1.WorkflowCrossNS/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkflowCrossNSForwardOpProcedure:
			workflowCrossNSForwardOpHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkflowCrossNSHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkflowCrossNSHandler struct{}

func (UnimplementedWorkflowCrossNSHandler) ForwardOp(context.Context, *connect.Request[v1.ForwardOpRequest]) (*connect.Response[v1.ForwardOpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dapr.proto.internals.v1.WorkflowCrossNS.ForwardOp is not implemented"))
}
