global:
  registry: docker.io/daprio
  tag: 'edge'
  dnsSuffix: ".cluster.local"
  logAsJson: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ""
  nodeSelector: {}
  tolerations: []
  ha:
    enabled: false
    replicaCount: 3
    disruption:
      minimumAvailable: ""
      maximumUnavailable: "25%"
  prometheus:
    enabled: true
    port: 9090
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m
    caFile: ca.crt
  daprControlPlaneOs: linux
  labels: {}
  controlPlaneTrustDomain: "cluster.local"
  k8sLabels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Values.global.tag }}"
    app.kubernetes.io/part-of: "dapr"
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/component: "{{ .Values.component }}" # Should be set in each subchart
